### ISSUE TITLE
Was this deprecated in favor of something else?

### ISSUE THREAD

**Issue by ezefarina** [docker/jenkins-pipeline-scripts#26]
Couldn't find any related info on why this repo was deprecated and if it was or not in favor of a newer one

**Comment by jdkelley** [comment]
I am also curious about this. @ezefarina, have you heard anything since opening this issue?

**Comment by psftw** [comment]
In a nutshell, we started over with a private repository keeping only some of the functions here.  We also needed to add functionality that would be highly coupled to our infrastructure/process that could not be abstracted out for general use. It was easier to start over than maintain both public and private scripting libraries.
