### ISSUE TITLE
withTool improvements

### ISSUE THREAD

**Issue by mikedougherty** [docker/jenkins-pipeline-scripts#9]
Current implementation is hackish and probably only works for the tool configurations we're using in-house. 

per @jglick https://github.com/docker/jenkins-pipeline-scripts/commit/3a4b6f673f30ba0859f34192b27629e74c110d3f#commitcomment-19615153

there is also the newer `envVarsForTool()` function which will likely reduce the complexity of the implementation.

**Comment by psftw** [comment]
closing stale
